name: A workflow for my Hello World actions file
on: push

jobs:
  build:
    
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          INPUT_MY_NAME: "Sagar"
